name: chatapp_client
description: Starting point for a Serverpod client.
resolution: workspace

environment:
  sdk: '^3.8.0'

dependencies:
  serverpod_auth_idp_client: 3.3.1
  serverpod_client: 3.3.1