services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: tmp_lasta
      POSTGRES_PASSWORD: "ChK_YK6q5YxTTzCF8HXSXJ_uImdZCjKp"
    volumes:
      - tmp_lasta_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "UCVWvN8UPkDzeNBCQoDsdM-g7mYq4L0r"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: tmp_lasta_test
      POSTGRES_PASSWORD: "qoshnvTtwCHHgCLyIzCJaa1oTAXBqZbk"
    volumes:
      - tmp_lasta_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "NwwzSgSY1lT5J-ttYuql6ZTm7B5br1UT"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  tmp_lasta_data:
  tmp_lasta_test_data:
